<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="FooTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2017-05-22T23:22:42" hostname="DESKTOP-0010" time="0.015">
  <properties/>
  <testcase name="constructorCalled_innerObjectNull_ThrowsException" classname="FooTest" time="0.015"/>
  <testcase name="constructorCalled_bothParamsNull_ThrowsException" classname="FooTest" time="0.0"/>
  <testcase name="constructorCalled_ValidParams_FooCreated" classname="FooTest" time="0.0"/>
  <testcase name="constructorCalled_innerObjectNullField_ThrowsException" classname="FooTest" time="0.0"/>
  <testcase name="constructorCalled_innerObjectCanBeNullFalseWithNullField_NoException" classname="FooTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[May 23, 2017 9:22:42 AM net.sf.oval.internal.Log info
INFO: Instantiated
]]></system-err>
</testsuite>
